CREATE TABLE EMPS(
	ID CHAR(10),
	NAME CHAR(20),
	AGE INT
);

INSERT INTO EMPS VALUES ('ID01', '이말숙',20);
INSERT INTO EMPS VALUES ('ID02', '이말숙',30);
INSERT INTO EMPS VALUES ('ID03', '이말숙',40);

SELECT * FROM EMPS;

DROP TABLE EMPS;